spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
application:
  file: ./files/
  fonts: fonts/TimesNewRoman.ttf